$(call import-module, libguiex_core)
$(call import-module, libguiex_module)
$(call import-module, libguiex_widget)
$(call import-module, libguiex_widget_box2d)
$(call import-module, libguiex_widget_game)
$(call import-module, libguiex_script_wrapper)
$(call import-module, libguiex_framework)
$(call import-module, external/Box2D)
$(call import-module, external/lua)
$(call import-module, external/tinyxml)
$(call import-module, external/freetype)
$(call import-module, external/libzip)

